### ISSUE TITLE
Persian language

### ISSUE THREAD

**Issue by HazemKhaled** [Magento2Translations/Magento2Translations.github.io#1]
It'll be great to create repo for Persian language

https://crowdin.com/project/magento2-persian-language

Thanks

**Comment by MrGekko** [comment]
Nice, it would be a beter idea to ask [MagentoTranslations](https://crowdin.com/profile/MagentoTranslations) to add Persian to the main Magento2 translations. 
I think the Finish language was added this way.

And secondly, I cannot download the sources from that project?!? And they don't use the same branching in the project. Maybe we could make this work, but it would require some effort from the [Magento2 Persian Language project owner](http://translate.magento-farsi.com/project/magento2-persian-language?accepted=12970244).

It would be best if all the translating effort went into the official crowdin project.

**Comment by HazemKhaled** [comment]
I already sent msg to both of them, Magento and Magento2 Persian team, waiting their reply

Thanks

**Comment by HazemKhaled** [comment]
Persian arrived man, create you new repo :)
https://crowdin.com/project/magento-2/fa#

**Comment by MrGekko** [comment]
Cool! all done :) I have added Vietnamese, Chinese(Taiwan) and Catalan too.
